version: '3'
services:
  mediawiki:
    container_name: mediawiki
    image: mediawiki:1.39
    restart: always
    ports:
      - 8080:80
    depends_on:
      - database
    volumes:
      - ./skins:/var/www/html/skins
      - ./images:/var/www/html/images
      # - ./LocalSettings.php:/var/www/html/LocalSettings.php
    networks:
      - mediawiki_network
  database:
    container_name: mediawiki_db
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: my_wiki
      MYSQL_USER: wikiuser
      MYSQL_PASSWORD: wikipassword
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - mediawiki_network
networks:
  mediawiki_network:
    driver: bridge