version: '3'
services:
  portainer:
    image: portainer/portainer-ce:latest  
    command: -H unix:///var/run/docker.sock
    privileged: true  
    ports:
      - '9000:9000'
    volumes:
      - './data:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
    restart: always